### PR TITLE
Meaningful first_seen date

### LINKED ISSUE #381: Make first_seen first seen
Currently, the AIP report includes a first_seen date reporting the date a variant was first reported. However, the reported date reflects the most recent date a new category was added to a variant.

Proposal: 
 - Refine `first_seen` to be the date a variant was first identified by the AIP. This should not change over time.
 - Add new value to report `evidence_last_updated` reporting the most recent date a new category was applied to a variant.
 - Consider adding `date_of_phenotype_match` indicating the earliest date there was a phenotype match (of any kind) found for a variant.
 - Consider changing  `first_seen` name to `first_tagged` to match seqr language. TBH neither are great, but consistent non-greatness might be better than inconsistent non-greatness.

### PR DESCRIPTION
**Pull request by MattWellie**
# Fixes

  - Ugh, this was a real rabbithole
  - Closes #381

## Proposed Changes

  - The Phenotype object in the data model is now codified as a PhenoPacketHpo object, with `id` and `label` attributes
  - `stratify_solved_cases.py` uses the `sequencing_group` attributes instead of the metadata content. Not relevant to this PR, but this is relevant to https://github.com/populationgenomics/production-pipelines/issues/717
  - Model liftover script for None -> `1.0.0` improved
  - Model liftover script for `1.0.0` -> `1.0.1` created
  - Upgrade some uses of get_config to config_retrieve
  - Added a whole bunch of test JSON

Hopefully this should accomplish:

 - Both AIP reports and the 'historic data' files have first_tagged datestamps. If the historic data is read in from an earlier version, the 'first_tagged' date is the earliest of all category timestamps. This first_tagged date is a fixed point in time for each variant (not variant * category, or variant * support variant)
 - `evidence_last_updated` exists in the model. If Historic data is supplied, this is the latest date of any category applied. If no historic data is supplied this becomes `today` for every variant
 - `date_of_phenotype_match` exists in the model, but isn't yet populated. The logic for that will be included with #390

## Checklist

- [x] Related Issue created
- [x] Tests covering new change
- [x] Linting checks pass

### CODE REVIEW

**Comment by MattWellie** [comment]
Planning to get a test run of this done before changing from draft

**Review by cassimons — APPROVED** [review]
Legend!

**Comment by MattWellie** [comment]
Needed a quick tweak on the template, but https://batch.hail.populationgenomics.org.au/batches/445612 was run using this code state and it all looks good!

**Comment by MattWellie** [comment]
Bonus changes - the latest history files are now picked up via the datetimes embedded in the filenames, not by the modified date which has been shown to be unreliable

**Pull request merged**
